### ISSUE TITLE
Talk at FrankfurtJS 

### ISSUE THREAD

**Issue by patrickwieth** [cookiengineer/ANN-Guide#1]
Hey,

will you give this as a talk at #9 FrankfurtJS, more precisely the question is, if you are available at this evening?

**Comment by terehov** [comment]
Hi Christoph, 

its already in a week. I would need your feedback asap. 

cheers

**Comment by cookiengineer** [comment]
Oh gosh, it is somehow funny that I do not watch my own projects by default when they are created. Haven't seen this message, but I'm glad the other channels worked.

Sorry guys <3
